import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:investment/widget/custom_appbar.dart';

class CompanyInfomation  extends StatelessWidget {
  const CompanyInfomation ({super.key});

  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: kAppBar(title: 'Information') ,
      body: SingleChildScrollView(
        physics:const BouncingScrollPhysics(),
        child: Padding(
          padding: const EdgeInsets.all(12.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Company Profile',style: TextStyle(
                fontSize: 21.sp,
                letterSpacing: 2,
                fontWeight: FontWeight.w400,
              )),
      
              SizedBox(height: 15.h,),
              Container(
                padding: EdgeInsets.symmetric(vertical: 13.h,horizontal: 20.w) ,
                decoration: BoxDecoration(color: Colors.blue.withOpacity(0.1),
                borderRadius: BorderRadius.all(Radius.circular(10.r))),
                child: Text('Sutraq company was established on September 2023. We have long term providd mining equipment for the development of USDT. For stable and efficient cryptocurrency mining, we  have been providing out equipment for the target group of users who do not have to build mining farms, learn algorithms and pay large electricity bills.\n\n [Earn efficient income through simple operations]',style: TextStyle(fontSize: 15.sp),),
                ),
      
                SizedBox(height: 20.h,),
      
                Text('About us',style: TextStyle(
                fontSize: 21.sp,
                letterSpacing: 2,
                fontWeight: FontWeight.w400,
              )),
      
              SizedBox(height: 15.h,),
      
              Container(
                padding: EdgeInsets.symmetric(vertical: 13.h,horizontal: 20.w) ,
                decoration: BoxDecoration(color: Colors.blue.withOpacity(0.1),
                borderRadius: BorderRadius.all(Radius.circular(10.r))),
                child: Text('Sutraq subsidiary has pledged 12 billion USDT on Binance since Septeber 1, 2023, becoming the first USDT super represetative on TRON. In addition, Binance also supports USDT staking starting on September 1. Users who own USDT have the opportunity to share in the block rewards generated by all super representatives on the USDT network....',style: TextStyle(fontSize: 15.sp),),
                ),
      
                SizedBox(height: 15.h,),
      
                Text('Privacy Policy',style: TextStyle(
                fontSize: 21.sp,
                letterSpacing: 2,
                fontWeight: FontWeight.w400,
              )),
      
              SizedBox(height: 15.h,),
      
              Container(
                padding: EdgeInsets.symmetric(vertical: 13.h,horizontal: 20.w) ,
                decoration: BoxDecoration(color: Colors.blue.withOpacity(0.1),
                borderRadius: BorderRadius.all(Radius.circular(10.r))),
                child: Text('Sutraq subsidiary has pledged 12 billion USDT on Binance since Septeber 1, 2023, becoming the first USDT super represetative on TRON. In addition, Binance also supports USDT staking starting on September 1. Users who own USDT have the opportunity to share in the block rewards generated by all super representatives on the USDT network....',style: TextStyle(fontSize: 15.sp),),
                ),
              
            ],
          ),
        ),
      ),
    );
  }
}